name: Spring Boot & Gradle CI Jobs (With dev branches pull_request)

on:
  push:
    branches: [ dev ]
    paths:
      - 'src/**'

jobs:
  build:
    # 실행 환경
    runs-on: [self-hosted, urdego]
    steps:
      - uses: actions/checkout@v3

      # JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # resources 폴더 생성
      - name: resources 폴더 생성
        run: |
          mkdir -p ./src/main/resources

      # yml 파일 생성
      - name: yml 파일 생성
        run: |
          echo "${{ secrets.USER_APPLICATION_DEFAULT }}" >> ./src/main/resources/application.yml
          echo "${{ secrets.USER_APPLICATION_PROD }}" >> ./src/main/resources/application-prod.yml
          echo "${{ secrets.USER_APPLICATION_DB }}" >> ./src/main/resources/database-prod.yml

      # gradlew 실행 권한 부여
      - name: Gradlew 실행권한 부여
        run: chmod +x ./gradlew

      # 빌드
      - name: 빌드
        run: ./gradlew clean build -x test
